core/core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.decorators.cache import cache_page

from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi
from rest_framework.documentation import include_docs_urls
from .views import WeatherView, WeatherAPIView
from accounts import views

schema_view = get_schema_view(
    openapi.Info(
        title="ToDo API",
        default_version="v1",
        description="ToDo API documentation",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="saleh.mohammadzadeh@gmail.com"),
        license=openapi.License(name="MIT License"),
    ),
    public=True,
    permission_classes=[permissions.AllowAny],
)


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("todo.urls")),
    path("accounts/", include("accounts.urls")),
    path("signup", views.SignupCreateView.as_view(), name="signup"),
    path("api-auth/", include("rest_framework.urls")),
    path("api-docs/", include_docs_urls(title="API Documentation")),
    path(
        "swagger.json",
        schema_view.without_ui(cache_timeout=0),
        name="schema-json",
    ),
    path(
        "swagger.yaml",
        schema_view.without_ui(cache_timeout=0),
        name="schema-yaml",
    ),
    path(
        "swagger/",
        schema_view.with_ui("swagger", cache_timeout=0),
        name="schema-swagger-ui",
    ),
    path(
        "redoc/",
        schema_view.with_ui("redoc", cache_timeout=0),
        name="schema-redoc",
    ),
    path(
        "weather/",
        cache_page(60 * 20)(WeatherView.as_view()),
        name="weather",
    ),
    path("weather/api/", WeatherAPIView.as_view(), name="api-weather"),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.STATIC_URL, document_root=settings.STATIC_ROOT
    )
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

core/todo/api/v1/urls.py
from rest_framework.routers import DefaultRouter
from . import views

router = DefaultRouter()
router.register("task", views.TaskModelViewSet, basename="task")

app_name = "api-v1"
urlpatterns = router.urls

core/todo/urls.py
from django.urls import path, include
from . import views

app_name = "todo"


urlpatterns = [
    path("", views.TaskListView.as_view(), name="index"),
    path("add/", views.TaskCreateView.as_view(), name="add"),
    path("<int:pk>/done/", views.TaskDoneUpdateView.as_view(), name="done"),
    path("<int:pk>/delete/", views.TaskDeleteView.as_view(), name="delete"),
    path("<int:pk>/edit/", views.TaskEditView.as_view(), name="edit"),
    path("api/v1/", include("todo.api.v1.urls")),
]

core/todo/models.py
from django.db import models
from django.contrib.auth import get_user_model

# getting the user model object
User = get_user_model()


class Task(models.Model):
    """
    this is a class for tasks in our todo app
    """

    author = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.CharField(max_length=255)
    is_done = models.BooleanField(default=False)
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["-created_date"]

    def __str__(self):
        return "{} - {}".format(self.author, self.content)

    def get_snippet(self):
        return self.content[:10]

core/todo/forms.py
from django.forms import ModelForm
from .models import Task


class TaskForm(ModelForm):
    class Meta:
        model = Task
        fields = ["content"]

core/todo/api/v1/views.py
from rest_framework import viewsets
from rest_framework.permissions import IsAuthenticated
from django_filters.rest_framework import DjangoFilterBackend
from rest_framework.filters import SearchFilter, OrderingFilter
from .paginations import CustomPagination
from todo.models import Task
from .serializers import TaskSerializer
from .permissions import IsVerified


class TaskModelViewSet(viewsets.ModelViewSet):
    """
    A simple ModelViewSet to perform CRUD functions on todo Task.
    """

    serializer_class = TaskSerializer
    permission_classes = [IsAuthenticated, IsVerified]
    filter_backends = [DjangoFilterBackend, SearchFilter, OrderingFilter]
    filterset_fields = ["is_done"]
    search_fields = ["content"]
    ordering_fields = ["created_date"]
    pagination_class = CustomPagination

    def get_queryset(self):
        """
        This view should return a list of all the tasks
        for the currently authenticated user.
        """
        user = self.request.user
        return Task.objects.filter(author=user)

core/todo/views.py
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from django.shortcuts import get_object_or_404, redirect
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Task
from .forms import TaskForm


class TaskListView(LoginRequiredMixin, ListView):
    """
    This is a view class that show the task created by each user that logged in
    """

    allow_empty = True
    template_name = "todo/index.html"
    context_object_name = "tasks"

    def get_queryset(self):
        tasks = Task.objects.filter(author=self.request.user)
        return tasks


class TaskCreateView(LoginRequiredMixin, CreateView):
    """
    This is a view that create new task for user
    """

    template_name = reverse_lazy("todo:index")
    form_class = TaskForm
    field = ["content"]
    success_url = reverse_lazy("todo:index")

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


class TaskDoneUpdateView(LoginRequiredMixin, UpdateView):
    """
    This is a view that change the status (is_done) of task to True
    """

    model = Task
    template_name = reverse_lazy("todo:index")

    def get(self, request, pk, *args, **kwargs):
        task = get_object_or_404(Task, pk=pk)
        if task.author == self.request.user:
            task.is_done = True
            task.save()
        return redirect(reverse_lazy("todo:index"))


class TaskDeleteView(LoginRequiredMixin, DeleteView):
    """
    This a is class that delete a task
    """

    success_url = reverse_lazy("todo:index")

    def get_queryset(self):
        tasks = Task.objects.filter(author=self.request.user)
        return tasks


class TaskEditView(LoginRequiredMixin, UpdateView):
    """
    This is a class that edit a task content
    """

    form_class = TaskForm
    success_url = reverse_lazy("todo:index")
    template_name = "todo/task_edit.html"

    def get_queryset(self):
        tasks = Task.objects.filter(author=self.request.user)
        return tasks

core/templates/todo/index.html
{% load humanize %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Todo app</title>
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css"
      integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N"
      crossorigin="anonymous"
    />
  </head>
  <body>
    <div class="container">
      <div class="justify-content-md-center">
        <div class="mt-5 mb-4">
          <center><h3>Hello {{request.user.email}}, Your Todo List is below</h3></center>
        </div>
        <div class="mt-5 mb-4">
          <form action="{% url 'todo:add' %}" method="post">
            {% csrf_token %}
            <div class="input-group mb-3">
              <input type="text" class="form-control" name="content" placeholder="Type your new task here!" required >
              <div class="input-group-append">
                <button type="submit" class="btn btn-primary">Add</button>
              </div>
            </div>
          </form>
          <a href="{% url 'accounts:logout' %}">logout</a>
          {% if not tasks %}
            <br>
            <p>There is no task</p>
          {% else %}
          <table class="table table-hover">
            <thead>
              <tr>
                <th scope="col">No.</th>
                <th scope="col">Content</th>
                <th scope="col">Created</th>
                <th scope="col">Updated</th>
                <th></th>
              </tr>
            </thead>
            <tbody>

          {% for task in tasks %}

          
            {% if task.is_done %}
            <tr>
              <th scope="row">{{ forloop.counter }}</th>
              <td><del> {{task.content}}</del></td>
              <td>{{ task.created_date|naturaltime }}</td>
              <td>{{task.updated_date|naturaltime}}</td>
              <td>
                <div class="btn-group" role="group" aria-label="Basic example">
                  <a href="#" role="button" class="btn btn-success btn-sm disabled mb-1">Done</a>
                  <a href="#" role="button" class="btn btn-warning btn-sm disabled mb-1">Edit</a>
                  <a href="{% url 'todo:delete' pk=task.id %}" role="button" class="btn btn-danger btn-sm mb-1">Delete</a>
                </div>
              </td>
            </tr>
            {% else %}
            <tr>
              <th scope="row">{{ forloop.counter }}</th>
              <td>{{task.content}}</td>
              <td>{{ task.created_date|naturaltime }}</td>
              <td>{{task.updated_date|naturaltime}}</td>
              <td>
                <div class="btn-group" role="group" aria-label="Basic example">
                  <a href="{% url 'todo:done' pk=task.id %}" role="button" class="btn btn-success btn-sm mb-1">Done</a>
                 <a href="{% url 'todo:edit' pk=task.id %}" role="button" class="btn btn-warning btn-sm mb-1">Edit</a>
                 <a href="{% url 'todo:delete' pk=task.id %}" role="button" class="btn btn-danger btn-sm mb-1">Delete</a>
                </div>
              </td>
            </tr>
            {% endif %}
            <br>
          
          {% endfor %}
          {% endif %}
        </tbody>
      </table>
        </div>
      </div>
    </div>
  </body>
</html>

core/templates/todo/task_confirm_delete.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Confirm Delete</title>
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css"
      integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N"
      crossorigin="anonymous"
    />
  </head>
  <body>
    <div class="container justify-content-md-center">
      <div class="mt-5 mb-4">
        <form method="post">
          {% csrf_token %}
          <p>Are you sure you want to delete "{{ object.content }}"?</p>
          <input type="submit" class="btn btn-primary" value="Confirm" />
        </form>
      </div>
    </div>
  </body>
</html>

core/templates/todo/task_edit.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Confirm Delete</title>
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css"
      integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N"
      crossorigin="anonymous"
    />
  </head>
  <body>
    <div class="container justify-content-md-center">
      <div class="mt-5 mb-4">
        <form method="post">
          {% csrf_token %}
          <h2>Edit task</h2>
          {{ form.as_p }}
          <input type="submit" class="btn btn-primary" value="Confirm" />
        </form>
      </div>
    </div>
  </body>
</html>